### ISSUE TITLE
Feedback for the Readme

### ISSUE THREAD

**Issue by kraiskil** [GrandFatherADI/BurstStats#1]
I just tried BurstStats, works great, thanks!

I would have two updates to the documentation:

I noticed that when installing BurstStats via the Logic tool, and editing the user parameters in the python file the new values are not taken into use until I disable and re-enable the BurstStats extension. (For local extensions there is a "reload" button, but for downloaded extensions, this is missing).

On Linux, the BurstStats extension got installed to the `~/.config/Logic/Marketplace/64/` directory.

**Comment by GrandFatherADI** [comment]
Documentation updated in V1.0.3. Change should be in the Market Place now.

@kraiskil can you review and close this ticket if appropriate please?

**Comment by kraiskil** [comment]
Looks good to me, thanks.
